// src/components/eventpage/timeline.tsx
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

interface TimelineEvent {
  time?: string;
  title: string;
  desc?: string;
  author?: string;
}

interface TimelineDay {
  date: string;
  event: TimelineEvent[];
}

interface Timeline {
  title?: string;
  events: TimelineDay[];
}

type TimelineType = Timeline[];

export default function Timeline({ timeline }: { timeline: TimelineType }) {
  const outerTabs = timeline.map((_) => (
    <TabsTrigger value={_.title ?? ''} key={_.title} className="w-full">
      {_.title}
    </TabsTrigger>
  ));

  const content = timeline.map((event) => (
    <TabsContent value={event.title ?? ''} key={event.title}>
      <Tabs defaultValue={event.events[0].date}>
        <TabsList className="w-full">
          {event.events.map((dateEvent) => (
            <TabsTrigger value={dateEvent.date} key={dateEvent.date} className="w-full">
              {dateEvent.date}
            </TabsTrigger>
          ))}
        </TabsList>
        {event.events.map((dateEvent) => (
          <TabsContent value={dateEvent.date} key={dateEvent.date} className="mx-3 mt-4">
            <ol className="relative border-l border-slate-800">
              {dateEvent.event.map((ev, eventIndex) => (
                <li key={`${dateEvent.date}-${eventIndex}`} className="ml-4 mt-2">
                  <div className="absolute w-3 h-3 bg-gray-200 rounded-full mt-1.5 -left-1.5 border border-slate-800 bg-slate-700" />
                  <time className="mb-1 text-sm text-slate-400">{ev.time}</time>
                  <h3>{ev.title}</h3>
                  <p className="text-slate-200 leading-normal my-0.5">{ev.desc}</p>
                  <p className="text-slate-400 text-sm">{ev.author}</p>
                </li>
              ))}
            </ol>
          </TabsContent>
        ))}
      </Tabs>
    </TabsContent>
  ));

  return (
    <Tabs defaultValue={timeline[0].title || ''}>
      {timeline[0].title && <TabsList className="w-full">{outerTabs}</TabsList>}
      {content}
    </Tabs>
  );
}

// components/events/timeline.vue
<template>
  <div v-for="day in timeline" :key="day.date" class="not-prose">
    <h2 class="text-2xl font-semibold tracking-tight text-gray-900 sm:text-3xl dark:text-white">{{ day.date }}</h2>
    <ol class="relative border-l border-gray-200 dark:border-gray-700 mb-3">
      <li v-for="event in day.events" :key="event.time" class="mb-10 ml-4">
        <div class="absolute w-3 h-3 bg-gray-200 rounded-full mt-1.5 -left-1.5 border border-white dark:border-gray-800 dark:bg-gray-600" />
        <time class="mb-1 text-sm font-normal leading-none text-gray-400 dark:text-gray-400">{{event.time }}</time>
        <h3 class="text-lg font-semibold tracking-tight text-gray-900 sm:text-xl dark:text-white">{{ event.title }}</h3>
        <!-- <p class="sm:text-lg text-md text-gray-600 dark:text-slate-300">
            {{ event.desc }}
        </p> -->

        <div class="flex items-center">
          <p class="sm:text-lg text-md grow text-gray-600 dark:text-slate-300">{{ event.desc }}</p>
          <NuxtLink v-if="event.youtube"
                    :href="event.youtube"
                    class="text-gray-500 hover:text-gray-900 dark:hover:text-white mx-4"
          >
            <IconsYoutube />
          </NuxtLink>
        </div>
        <p class="text-md text-gray-500 dark:text-slate-400">{{ event.author }}</p>
      </li>
    </ol>
  </div>
</template>

<script setup>
defineProps(['timeline'])
</script>
