// components/nav.vue
<template>
    <div class="sticky top-0 z-10">
        <header class="absolute inset-x-0 top-0 z-50">
            <nav class="bg-white dark:bg-slate-800 backdrop-filter backdrop-blur-lg bg-opacity-50 dark:bg-opacity-50 border-b border-gray-100 dark:border-slate-800 flex items-center justify-between p-6 lg:px-8"
                aria-label="Global">
                <div class="flex lg:flex-1">
                    <NuxtLink class="-m-1.5 p-1.5" to="/">
                        <span class="sr-only">BuildingBloCS</span>
                        <img class="h-8 w-auto" src="/logo.png" alt="" />
                    </NuxtLink>
                </div>
                <div class="flex lg:hidden">
                    <button type="button"
                        class="-m-2.5 inline-flex items-center justify-center rounded-md p-2.5 text-gray-700 dark:text-gray-300"
                        @click="mobileMenuOpen = true">
                        <span class="sr-only">Open main menu</span>
                        <Bars3Icon class="h-6 w-6" aria-hidden="true" />
                    </button>
                </div>
                <div class="hidden lg:flex lg:gap-x-12">
                    <NuxtLink v-for="item in navigation" :key="item.name" :href="item.href"
                        class="text-sm font-semibold leading-6 text-gray-900 dark:text-slate-200">{{ item.name }}</NuxtLink>
                </div>
                <div class="hidden lg:flex lg:flex-1 lg:justify-end">
                    <Mode />
                    <NuxtLink href="https://go.buildingblocs.sg/june"
                        class="hover:underline rounded-md bg-orange-500 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-orange-600 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-orange-500">
                        Register
                        <span aria-hidden="true">&rarr;</span>
                    </NuxtLink>
                </div>
            </nav>
            <Dialog as="div" class="lg:hidden" @close="mobileMenuOpen = false" :open="mobileMenuOpen">
                <div class="fixed inset-0 z-50" />
                <DialogPanel
                    class="fixed inset-y-0 right-0 z-50 w-full overflow-y-auto bg-white dark:bg-slate-800 px-6 py-6 sm:max-w-sm sm:ring-1 sm:ring-gray-900/10">
                    <div class="flex items-center justify-between">
                        <NuxtLink class="-m-1.5 p-1.5" to="/">
                            <span class="sr-only">BuildingBloCS</span>
                            <img class="h-8 w-auto" src="/logo.png" alt="" />
                        </NuxtLink>
                        <Mode />
                        <button type="button" class="-m-2.5 rounded-md p-2.5 text-gray-700 dark:text-slate-200" @click="mobileMenuOpen = false">
                            <span class="sr-only">Close menu</span>
                            <XMarkIcon class="h-6 w-6" aria-hidden="true" />
                        </button>
                    </div>
                    <div class="mt-6 flow-root">
                        <div class="-my-6 divide-y divide-gray-500/10">
                            <div class="space-y-2 py-6">
                                <NuxtLink v-for="item in navigation" :key="item.name" :href="item.href"
                                    class="-mx-3 block rounded-lg px-3 py-2 text-base font-semibold leading-7 text-gray-900 dark:text-gray-200 hover:bg-gray-50">
                                    {{
                                        item.name }}</NuxtLink>
                            </div>
                            <div class="py-6">
                                <NuxtLink href="https://go.buildingblocs.sg/june"
                                    class="-mx-3 block rounded-lg px-3 py-2.5 text-base font-semibold leading-7 text-gray-900 dark:text-gray-200 hover:bg-gray-50">
                                    Register
                                    <span aria-hidden="true">&rarr;</span>
                                </NuxtLink>
                            </div>
                        </div>
                    </div>
                </DialogPanel>
            </Dialog>
        </header>
    </div>
</template>
  
<script setup>
import { ref } from 'vue'
import { Dialog, DialogPanel } from '@headlessui/vue'
import { Bars3Icon, XMarkIcon } from '@heroicons/vue/24/outline'

const navigation = [
    { name: 'Home', href: '/' },
    { name: 'Events', href: '/events' },
    { name: 'Our Team', href: '/team' },
    { name: 'Our Partners', href: '/partners' },
]

const mobileMenuOpen = ref(false)
</script>

// src/components/nav.tsx
import {
    Popover,
    PopoverContent,
    PopoverTrigger,
} from "@/components/ui/popover";
import { Sheet, SheetContent, SheetTrigger } from "@/components/ui/sheet";
import { Separator } from "@/components/ui/separator";
import {
    HamburgerMenuIcon,
    ArrowRightIcon,
    ChevronDownIcon,
} from "@radix-ui/react-icons";
import {
    Modal,
    ModalHeader,
    ModalBody,
    ModalFooter,
} from "free-astro-components";

export default function Nav({ data }: { data: any[] }) {
    const mobileLinks = [
        {
            title: "Home",
            href: "/",
        },
        {
            title: "Our Partners",
            href: "/partners",
        },
        {
            title: "Our Team",
            href: "/team",
        },
        // {
        //     title: "Join Us",
        //     href: "/joinus",
        // },
    ];

    const events = [
        {
            title: "Coming soon",
            href: "https://buildingblocs.notion.site/343104f6313d80c8a3f2da6bded7b2cf",
            desc: "Join the newsletter to get notified",
        },
        {
            title: "Looking for older events?",
            href: "/archive",
        },
    ];

    const mobileEvents = events.slice(0, -1);

    return (
        <>
            <div className="justify-center h-16 sm:flex hidden sticky top-0 z-20 gap-x-4">
                <div className="h-16 justify-end flex sticky top-0 z-20">
                    <div className="px-6 rounded-full mt-4 bg-slate-900/50 backdrop-filter backdrop-blur-lg ring-slate-800 flex items-center gap-x-2">
                        <a href="/">
                            <img
                                src="/favicon.svg"
                                alt="BuildingBloCS logo"
                                className="w-5 h-5 mr-1"
                            />
                        </a>
                        <a
                            href="/partners"
                            className="text-sm font-medium rounded-md px-2 transition hover:bg-white hover:text-black"
                        >
                            Our Partners
                        </a>
                        <a
                            href="/team"
                            className="text-sm font-medium rounded-md px-2 transition hover:bg-white hover:text-black"
                        >
                            Our Team
                        </a>
                        {/* <a
                            href="/joinus"
                            className="text-sm font-medium rounded-md px-2 transition hover:bg-white hover:text-black"
                        >
                            Join Us
                        </a> */}

                        <Popover>
                            <PopoverTrigger className="translate-y-0 translate-x-0 text-sm font-medium rounded-md px-2 flex items-center gap-x-1 outline-0 group transition hover:bg-white hover:text-black data-[state=open]:bg-slate-700">
                                Events
                                <ChevronDownIcon className="transition group-data-[state=open]:rotate-180 group-data-[state=open]:mt-0.5" />
                            </PopoverTrigger>
                            <PopoverContent className="max-w-xs p-2 flex flex-col mt-5 bg-slate-900 border-slate-700 text-white">
                                {data.map((event) => (
                                    <a
                                        href={event.href}
                                        className="font-semibold hover:bg-slate-800 p-2 rounded-md text-sm transition"
                                        key={event.title}
                                    >
                                        {event.title}
                                        {event.desc && (
                                            <p className="font-normal">
                                                {event.desc}
                                            </p>
                                        )}
                                    </a>
                                ))}
                            </PopoverContent>
                        </Popover>
                    </div>
                </div>
                {
                    <a
                        className="h-16 justify-end flex sticky top-0 z-20"
                        href="/events/june"
                    >
                        <div className="pl-5 pr-2.5 rounded-full mt-4 bg-slate-900/50 backdrop-filter backdrop-blur-lg ring-1 ring-slate-800 flex items-center gap-x-4">
                            <p>Register for June Jam</p>
                            <div className="bg-orange-500 hover:bg-orange-600 rounded-full p-1 px-1.5 transition flex gap-x-2 items-center font-semibold">
                                <ArrowRightIcon className="w-5 h-5" />
                            </div>
                        </div>
                    </a>
                }
            </div>
            {/* Mobile Nav */}
            <div className="sm:hidden h-16 justify-end flex sticky top-0 z-20">
                {
                    <a
                        href="/events/june"
                        className="px-6 py-2 rounded-full mt-4 mr-4 bg-slate-900/50 backdrop-filter backdrop-blur-lg ring-1 ring-slate-800 flex items-center gap-x-4 text-sm"
                    >
                        <p>Sign up for June Jam</p>
                        <div className="bg-orange-500 hover:bg-orange-600 rounded-full p-1 px-1.5 transition flex gap-x-2 items-center font-semibold">
                            <ArrowRightIcon className="w-5 h-5" />
                        </div>
                    </a>
                }
                <div className="px-6 py-2 rounded-full mt-4 mr-4 bg-slate-900/50 backdrop-filter backdrop-blur-lg ring-1 ring-slate-800 flex items-center gap-x-4">
                    <a href="/">
                        <img
                            src="/favicon.svg"
                            alt="BuildingBloCS logo"
                            className="w-5 h-5"
                        />
                    </a>
                    <Separator
                        orientation="vertical"
                        className="bg-slate-800"
                    />
                    <Sheet>
                        <SheetTrigger aria-label="Navigation Menu">
                            <HamburgerMenuIcon />
                        </SheetTrigger>
                        <SheetContent>
                            <div className="flex flex-col justify-center h-full text-xl gap-y-2 font-medium relative">
                                {mobileLinks.map((link) => (
                                    <a href={link.href} key={link.title}>
                                        {link.title}
                                    </a>
                                ))}
                                {data.map((event) => (
                                    event.title !== "Coming Soon" && (
                                        <a href={event.href} key={event.title}>
                                        {event.title}
                                    </a>
                                    )
                                ))}
                            </div>
                        </SheetContent>
                    </Sheet>
                </div>
            </div>
        </>
    );
}
